### PR TITLE
Milestone one ERD Docs

### PR DESCRIPTION
**Pull request by Rashad-Muntar**
Milestone 1: Prepare data architecture documentation
We documented the association of the following models using the Lucid app below;

Users Table
Comments Table
Likes Table
Friendship Table
Post Table

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi team!
Nice start:clap::clap:.** 

Highlights
The PR is very descriptive

**To improve**

- [x] Friendship table

- Make a second link(association) to the Users table. Just like the first one.

- [x] User table

- It should have ID, name, and image_link column. Every other column is not needed and should be deleted.

- [x] Post table

- A user should have many posts. And a post should belong to a user. So the many symbol of the link should connect to Post table.
- The relationship between Post and Comment should be one-to-many. And not many-to-many. Replace the many symbol that connects to the Post table with a belong-to symbol.

- [x] All tables
- Replace `id` with `ID` for all PK's
- Each table name should start with a capital letter

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Comment by FdI96** [comment]
Done, It was just a confusion in the arrows, now I made them clear and created the new association

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi Team 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
-  Friendship table
- [x] The second association is not like the first one. Make a second link(association) to the Users table. Just like the first one. (As previous TSE suggested)

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by enaburekhan — APPROVED** [review]
# Status: Approve:heavy_check_mark:
**Hi team!
Congratulations on this milestone:clap::clap:. Thank you for implementing the changes requested by the last reviewer. Move on with the next milestone:walking:.**


Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Pull request merged**
