### PR TITLE
Milestone Friendshipv1

### PR DESCRIPTION
**Pull request by Rashad-Muntar**
We implemented this features as per the instructions

- Display all users.
- Selected user page with their user name and all posts written by them (the most recent posts on the top).
- Ability to send Friendship invitation.
- “Invite to friendship” button next to the name of the user who is not my friend yet - on both users’ list and single user page.
- User is able to see pending friendship invitations sent to me as a user.
- Able to accept or reject friendships invitation.
- Able to create new posts (text only).
- Able to like/dislike posts (but can like single post only once).
- Able to add comments to posts.
- Able to see “Timeline” page with posts (with number of likes and comments) written by me and all my friends (the most recent - posts on the top).
- Timeline page is the root page of the app.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

## Hello @Rashad-Muntar  and @FdI96  good job with this millstone :clap: 

### To highlight:
- Good job with the models :+1: 


### To improve:

- [x] I cannot reject a friendship request because when I reject a friendship request I get the following error: `Routing Error No route matches [POST] "/friendships/1"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Good job with model tests but you should also include integration tests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] When `User A` sends friendship requests to `User B` and `User A` has one post so after the `User B` accepts the friendship request in his timeline it shows that the `User A` has created the same post two times which he didn't so the posts always double when in the timeline of the user that did not create them. So kindly fix this

_Please implement all the above mentioned requirements and ask for another code review whenever you are ready_

### **If you have any question related to the requirements please add a comment here and ping me on slack @GzimAsani**

# HAPPY CODING :computer: :desktop_computer:

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
--------------
Hello, @Rashad-Muntar @FdI96 You are doing an excellent job so far :+1: :muscle: 
However there is one problem to fix :hammer_and_wrench: see it below :eyes: :point_down: 
-----------
- [ ] When I try to run `rails db:migrate` i got the following error. 

Screenshot from 2021-04-27 19-24-48

Please fix this. 
----------------
Make the required changes and send it again for another review :muscle: 
HAPPY CODING!! :smile:

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Rashad-Muntar and @FdI96  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] When I tried to reject a friend request, the app crashed with the following error message
Screenshot from 2021-04-28 13-45-32

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED :green_circle: :clap: 
------------
Hello again :wave: great job working on the required changes. :muscle: :100: 
Your project is working correctly :1st_place_medal:
---------
Now you can merge this branch :smile: 
HAPPY CODING!! AND GOOD LUCK WITH THE NEXT MILESTONES :crossed_fingers: :four_leaf_clover: 

Well-Done-Applause

**Pull request merged**
